<a href="https://colab.research.google.com/github/sanelehlabisa/Intro-to-Torch/blob/main/Intro_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensors
- A torch tensor is a multi-dimention matrix containing elements of single data type.
- Similar to numpy arr but has lot benefits if they are used with a GPU.
- Default type is float32.
- More suitable for deep learning that numpy array.


In [1]:
import torch
import numpy as np

##Lists

In [2]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# Numpy arrays

In [3]:
numpy_array = np.random.rand(3,4)
numpy_array

array([[0.55640848, 0.82411287, 0.56640033, 0.72742344],
       [0.39908289, 0.05772546, 0.06250803, 0.4771029 ],
       [0.12929618, 0.52452949, 0.299285  , 0.12673563]])

In [5]:
numpy_array.dtype

dtype('float64')

## Tensor arrays

In [6]:
tensor_array = torch.rand(3,4)
tensor_array

tensor([[0.6066, 0.1549, 0.5647, 0.5318],
        [0.8960, 0.6152, 0.1708, 0.9434],
        [0.8992, 0.6771, 0.5570, 0.6960]])

In [7]:
tensor3d_array = torch.zeros(2,3,4)
tensor3d_array

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
## Create tensor from numpy

my_tensor = torch.tensor(numpy_array)
my_tensor

tensor([[0.5564, 0.8241, 0.5664, 0.7274],
        [0.3991, 0.0577, 0.0625, 0.4771],
        [0.1293, 0.5245, 0.2993, 0.1267]], dtype=torch.float64)

## Tensor operations

In [9]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# 1. Reshape
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
my_torch2 = torch.arange(10)
my_torch2 = my_torch2.reshape(-1,2)
my_torch2


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [28]:
# 2. View
my_torch3 = torch.arange(10)
my_torch3 = my_torch3.view(2,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

### Difference between torch viev and reshape
- Torch view creates a view of the original tensor and share same data.
- Whereas Torch reshape creates a copy of the orriginal tensor under some conditions resulting in a new tensor with different data.

In [32]:
# Both reshape and view, they will both update along our tensor
my_tensor4 = torch.arange(10)

my_tensor5 = my_tensor4.reshape(2,5)

my_tensor6 = my_tensor4.view(2,5)


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [35]:
my_tensor4[0] = 4141

print(my_tensor5)
print(my_tensor6)

# The change in my_tensor4 is reflected in both my_tensor5 and my_tensor6

tensor([[4141,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])
tensor([[4141,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])


In [37]:
# 3. Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
my_torch7[7]

tensor(7)

In [41]:
my_tensor8 = my_torch7.reshape(5, 2)
my_tensor8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [43]:
my_tensor8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [73]:
# 4. Addition

tensor_a = torch.tensor([1,2,3,4,5])
tensor_b = torch.tensor([6,7,8,9,10])

tensor_a + tensor_b


tensor([ 7,  9, 11, 13, 15])

In [45]:
# Addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 7,  9, 11, 13, 15])

In [46]:
# 5. Subtraction

tensor_b - tensor_a

tensor([5, 5, 5, 5, 5])

In [55]:
# Subtraction longhand

torch.subtract(tensor_b, tensor_a)

tensor([5, 5, 5, 5, 5])

In [56]:
# 6. Multiplication

tensor_a * tensor_b

tensor([ 6, 14, 24, 36, 50])

In [57]:
# Multiplication longhand

torch.multiply(tensor_a, tensor_b)

tensor([ 6, 14, 24, 36, 50])

In [58]:
# 7. Division

tensor_b / tensor_a

tensor([6.0000, 3.5000, 2.6667, 2.2500, 2.0000])

In [60]:
# Division longhand

torch.divide(tensor_b, tensor_a) # try torch.div()

tensor([6.0000, 3.5000, 2.6667, 2.2500, 2.0000])

In [61]:
# 8. Modulos

tensor_b % tensor_a

tensor([0, 1, 2, 1, 0])

In [62]:
# Modulus longhand

torch.remainder(tensor_b, tensor_a)

tensor([0, 1, 2, 1, 0])

In [64]:
# 9. Exponents

tensor_a ** tensor_b

tensor([      1,     128,    6561,  262144, 9765625])

In [65]:
# Exponents longhand

torch.pow(tensor_a, tensor_b)

tensor([      1,     128,    6561,  262144, 9765625])

In [67]:
# Note that torch.pow(a, b) = a.pow(b)
tensor_a.pow(tensor_b) # same as above

tensor([      1,     128,    6561,  262144, 9765625])

In [74]:
# 10. Reassignment

tensor_a = tensor_a + tensor_b
tensor_a

tensor([ 7,  9, 11, 13, 15])

In [76]:
# Reassignmnet Addition longhand

tensor_a.add_(tensor_b) # it's the same as tensor_a = tensor_a + tensor_b
tensor_a

tensor([19, 23, 27, 31, 35])